[package]
name = "macdive-toolbox"
version = "0.1.0"
authors = ["Morton Jonuschat <mjonuschat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
askama = "0.12.0"
async-trait = "0.1.50"
bytefmt = "0.1.7"
celes = "2.4.0"
change-case = "0.2.0"
chrono = "0.4.19"
clap = { version = "4.1.8", features = [ "derive" ] }
comfy-table = "7.1.0"
console = "0.15.5"
csv = "1.2.1"
dirs = "5.0.1"
entity = { path = "../entity" }
futures = "0.3.16"
geo = { version = "0.28.0", features = ["serde"] }
google_maps = "3.1.1"
governor = "0.6.3"
indicatif = "0.17.3"
itertools = "0.12.1"
libmtp-rs = { version = "0.7.7", git = "https://github.com/quebin31/libmtp-rs.git" }
maplit = "1.0.2"
migration = { path = "../migration" }
nom = "7.1.3"
nonzero_ext = "0.3.0"
once_cell = "1.7.2"
ptree = "0.4.0"
regex = "1.4.5"
rust_decimal = "1.9.0"
rust_decimal_macros = "1.9.0"
sea-orm = { version = "1.0", features = ["runtime-tokio-native-tls", "sqlx-sqlite"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_yaml = "0.9.19"
sqlx = { version = "0.8.6", features = [ "sqlite", "runtime-tokio-native-tls", "uuid", "json", "chrono" ] }
strum = { version = "0.26.1", features = ["derive"] }
surf = "2.2.0"
thiserror = "1.0.24"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-indicatif = "0.3.0"
tracing-subscriber = "0.3"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
walkdir = "2.3.2"
xml_serde = "1.4.1"
