//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use sea_orm::JsonValue;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "taxon_cache")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub taxon_id: i32,
    pub matched_name: String,
    pub taxon: JsonValue,
    pub downloaded_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
